Clean mvp
elagarrigue/AyDS23-Lisboa5 pull request #6
Opened 2023-05-10 19:56 UTC by AxelFontana

Modificacion de la estructura del paquete moredetails para que corresponda a una arquitectura Clean MVP.
El diagrama de clases esta suelto en el paquete moredetails

2023-05-11 19:20 UTC, elagarrigue requested changes
- Eliminar el sub paquete fulllogic
- Mover el inyector a un paquete injector
- El diagrama no debería estar en source, mover a docs
- Diagrama incorrecto, faltan los paquetes (no se ve la estructura de la arquitectura). Sacar el inyector, no agregar implementaciones si están en el mismo paquete q la interfaz. Ver home y el diagrama de especificación de la arquitectura.

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/presentation/MoreDetailsPresenter.kt
> +    private val artistDescriptionHelper: ArtistDescriptionHelper = MoreDetailsInjector.artistDescriptionHelper
Inyectar la dependencia vía constructor

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/presentation/MoreDetailsPresenter.kt
> +    override var uiState: MoreDetailsUiState = MoreDetailsUiState()
no debería tener una propiedad uiState, se construye el objeto al recibir la entidad del repositorio y se emite

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/presentation/MoreDetailsPresenter.kt
Revisar la indentación de esta clase

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/domain/Artist.kt
>  sealed class Artist {
mover a un paquete entities

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/domain/ArtistRepository.kt
> +interface ArtistRepository{
mover a un paquete repository

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/domain/ArtistRepository.kt
> +interface ArtistRepository{
Revisar indentación

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/domain/ArtistRepository.kt
> +internal class ArtistRepositoryImpl(
La implementación va en data, no en dominio (no cumple con la arquitectura)

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/data/local/sqldb/ArtistLocalStorageImpl.kt
> +private const val DB_NAME = "dictionary.db"
mover a constants

2023-05-11 19:20 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/data/external/artist/artists/ArtistExternalService.kt
> +package ayds.lisboa.songinfo.moredetails.fulllogic.data.external.artist.artists
eliminar paquete `artists`

2023-05-11 22:43 UTC, MartinVerniere commented
Todavia no esta listo, falta agregar el diagrama, hice click en re-review sin darme cuenta que nos faltaba lo del diagrama corregido

2023-05-12 18:18 UTC, elagarrigue requested changes
Diagrama: Falta el servicio externo, comparar con home. Falta relación indirecta presenter -> view

2023-05-12 18:18 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +        }.start()
No tiene un solo nivel de abstracción, el thread debería llamar a una sola función

2023-05-12 18:18 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/data/local/sqldb/ArtistLocalStorageImpl.kt
> +internal class ArtistLocalStorageImpl(
revisar indentación

2023-05-13 23:12 UTC, elagarrigue requested changes
- Diagrama: Falta la relación presenter depende de domain
- Mejorar la descripción del PR

2023-05-13 23:12 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +    private fun notifyObservable(artistName: String){
No es un buen nombre, no sólo hace eso. Mejor `fetchMoreDetails`

2023-05-15 16:20 UTC, elagarrigue requested changes
- La descripción del PR sigue siendo insuficiente. No es MVP puro. Describir los cambios hechos.
- Diagrama: Relación indirecta incorrecta en presentation.

2023-05-15 21:35 UTC, elagarrigue reviewed
Ahí quedó 👍🏽

2023-05-15 21:43 UTC, elagarrigue approved these changes
👍🏽

2023-05-15 21:44 UTC, merged